url: https://switchcase.ch
baseurl: ""

# Site settings
title: switchcase klg
email: info@switchcase.ch
description: "SwitchCase KLG Homepage"


# Team names, titles and social links
people:
- name: Manuel Jordan
  pic: 1
  position: Co-Founder, Python/C# Developer
  social:
    - title: link
      url: https://blog.einsteinserbe.ch
    - title: github
      url: https://github.com/EinsteinsErbe
    - title: linkedin
      url: https://www.linkedin.com/in/manuel-jordan-1350a8121

- name: Manuel Geissberger
  pic: 2
  position: Co-Founder, Web Developer
  social:
    - title: link
      url: https://saturn91.dev
    - title: github
      url: https://github.com/Saturn91
    - title: linkedin
      url: https://www.linkedin.com/in/manuel-geissberger-04a051155

- name: coming soon...
  pic: 3
  position: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/SwitchCaseKLG
  - title: github
    url: https://github.com/SwitchCaseKLG
  - title: linkedin
    url: https://www.linkedin.com/company/switchcase-klg

# Postal address (add as many lines as necessary)
address:
  - line: c/o Manuel Jordan
  - line: Jesuitenweg 36
  - line: 3902 Glis

# Build settings
markdown: kramdown
permalink: pretty